# Generated by Django 5.2.8 on 2025-11-30 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What needs to be done?', max_length=200)),
                ('due_date', models.DateField(help_text='When is this due?')),
                ('estimated_hours', models.PositiveIntegerField(default=2, help_text='How many hours will this take?', validators=[django.core.validators.MinValueValidator(1)])),
                ('importance', models.PositiveIntegerField(default=5, help_text='How important is this? (1=low, 10=critical)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of task IDs that must be done first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-importance', 'due_date'],
            },
        ),
    ]
